### ISSUE TITLE
Intel Bluetooth doesn't work neither with Openintelwireless kexts installed in the efi folder...anyone know how to solve it?

### ISSUE THREAD

**Issue by matteosanta** [csrutil/NUC8I5BEH#25]

**Comment by phi-alek** [comment]
Yes, you need to open the usb port for the Bluetooth to work. I did it with
hackintool.

matteosanta <notifications@github.com> schrieb am Sa., 5. Dez. 2020, 23:06:

**Comment by matteosanta** [comment]
thank you, how can I do it?

**Comment by wveilleux** [comment]
Hi, First of all, thank you so much to share your NUC experience on GitHub. It help me to upgrade my NUC8 to Big Sur :). But I have the exact same issue. IntelBluetooth was working on my NUC8 with Clover but since I boot with OpenCore 0.6.4 on Big Sur, it doesn't work. So, would you please help us to point out a web page to learn how to open the USB port with Hackintool ? Best Regards

**Comment by csrutil** [comment]
Because of the IntelBluetooth will require the HS10 usb port, and the USBPorts.kext don't include the port, so you guys can disbale the USBPorts.kext and have a try

- disable the USBPorts.kext
https://github.com/appleserial/NUC8I5BEH/blob/master/EFI/OC/Config.plist#L312

```
        <string>USBPorts.kext</string>
        <key>Comment</key>
        <string></string>
        <key>Enabled</key>
        <true/> # change it to false
        <key>ExecutablePath</key>
```

**Comment by csrutil** [comment]
@wveilleux @matteosanta Please try the latest EFI, I did some refinement! Thank you!

**Comment by wveilleux** [comment]
WOW ! Thank you so much csrutil ! It make it work for me :) Bluetooth is working properly now :)

**Comment by matteosanta** [comment]
Really thank you, I just tried to do what you suggested and everything works great. Really amazing guide
